### ISSUE TITLE
Allow the use of git-stored config files instead of specifying key/secret in the step

### ISSUE THREAD

**Issue by mikhail** [Mrono/step-elastic-beanstalk-deploy#1]
The step configuration could receive path for git-stored elastic beanstalk configuration files. The step config then would look something like this:

```
deploy:
    steps:
        - mrono/elastic-beanstalk-deploy:
            cred_file: ./.elasticbeanstalk/aws_credential_file
            conf_file: ./.elasticbeanstalk/config
```
