### ISSUE TITLE
The configuration file, "config", cannot be found.

### ISSUE THREAD

**Issue by tal-moshayov** [Mrono/step-elastic-beanstalk-deploy#2]
setting up this step yields the following error:

```
Checking if eb exists and can connect.
Encountered error while reading from file .elasticbeanstalk/config.
The configuration file, "config", cannot be found. Use the "init" command to create it.

failed: EB is not working or is not set up correctly.
```

However, there most certainly is a file called ".elasticbeanstalk/config"
Any tips how to recover here?

**Comment by Mrono** [comment]
Hmm, I'm not sure what would be happening with it, can you post your setup (removing sensitive info)?  I'll try and run through a setup to make sure nothing has changed

**Comment by tal-moshayov** [comment]
thx Mike! here's the conf file:

[global]
ApplicationVersionName=Sample Application
AwsCredentialFile=/Users/tal/.elasticbeanstalk/aws_credential_file
EnvironmentTier=WebServer::Standard::1.0
EnvironmentType=SingleInstance
InstanceProfileName=aws-elasticbeanstalk-ec2-role
OptionSettingFile=/Users/tal/dev/silo/.elasticbeanstalk/optionsettings.staging-env
RdsDeletionPolicy=Snapshot
RdsEnabled=No
RdsSourceSnapshotName=
ServiceEndpoint=https://elasticbeanstalk.us-east-1.amazonaws.com
SolutionStack=64bit Amazon Linux 2014.03 v1.0.9 running Ruby 2.1 (Passenger Standalone)

ApplicationName=Staging
DevToolsEndpoint=git.elasticbeanstalk.us-east-1.amazonaws.com
EnvironmentName=staging-env
Region=us-east-1
[branches]
elastic-beanstalk=silo-staging

[branch:elastic-beanstalk]
ApplicationVersionName=Sample Application
EnvironmentName=silo-staging
EnvironmentTier=WebServer::Standard::1.0
EnvironmentType=LoadBalanced
InstanceProfileName=aws-elasticbeanstalk-ec2-role
OptionSettingFile=/Users/tal/dev/silo/.elasticbeanstalk/optionsettings.silo-staging
RdsDeletionPolicy=Snapshot
RdsEnabled=No
RdsSourceSnapshotName=

**Comment by Mrono** [comment]
I'll try and duplicate this tonight, anything special about your wercker config?

**Comment by christophbeger** [comment]
Hi @Mrono. I got the same problem. My eb config looks different, though. 

```
branch-defaults:
  master:
    environment: teemee-production
global:
  application_name: Teemee
  default_ec2_keyname: teemee
  default_platform: Node.js
  default_region: eu-central-1
  profile: eb-cli
  sc: git
```

Running eb status from terminal find application and env and status is green. Am I missing something?

here my wrecker.yml

```
box: wercker/nodejs
# Build definition
build:
  # The steps that will be executed on build
  steps:
    # A step that executes `npm install` command
    - npm-install
deploy:
    steps:
        - mrono/elastic-beanstalk-deploy:
            key: $AWS_KEY
            secret: $AWS_SECRET
            app_name: Teemee
            env_name: $AWS_ENV
            region: eu-central-1a
```

Parameters are properly set via wercker.
